(define (problem fetch)
  (:domain fetch)
  (:objects robot1 - robot treat - object roomA roomB roomC roomD - room)
  (:init (at robot1 roomA)
         (at_obj treat roomD)
         (connected roomA roomB)
         (connected roomA roomC)
         (connected roomB roomA)
         (connected roomB roomD)
         (connected roomC roomA)
         (connected roomC roomD)
         (connected roomD roomB)
         (connected roomD roomC))
  (:goal (and (at robot1 roomA) (at_obj treat roomA)))
)
